[package]
name = "recreds"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v2023_04_20"}
halo2_gadgets = {version = "0.3.1", features = ["unstable-sha256-gadget"]}
bitvec = "1.0.1"
halo2curves = "0.4.0"
criterion = "0.5.1"
rand = "0.8.5"
rand_core = "0.6.4"